// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: api/discovery.proto

/*
Package api is a generated blademaster stub package.
This code was generated with kratos/tool/protobuf/protoc-gen-bm v0.1.

It is generated from these files:
	api/discovery.proto
*/
package api

import (
	"context"

	bm "github.com/bilibili/kratos/pkg/net/http/blademaster"
	"github.com/bilibili/kratos/pkg/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

// DiscoveryBMServer is the server API for Discovery service.
type DiscoveryBMServer interface {
}

var DiscoverySvc DiscoveryBMServer

// RegisterDiscoveryBMServer Register the blademaster route
func RegisterDiscoveryBMServer(e *bm.Engine, server DiscoveryBMServer) {
	DiscoverySvc = server
}
