// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: api/register.proto

/*
Package api is a generated blademaster stub package.
This code was generated with kratos/tool/protobuf/protoc-gen-bm v0.1.

It is generated from these files:
	api/register.proto
*/
package api

import (
	"context"

	bm "github.com/bilibili/kratos/pkg/net/http/blademaster"
	"github.com/bilibili/kratos/pkg/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

// RegisterBMServer is the server API for Register service.
type RegisterBMServer interface {
}

var RegisterSvc RegisterBMServer

// RegisterRegisterBMServer Register the blademaster route
func RegisterRegisterBMServer(e *bm.Engine, server RegisterBMServer) {
	RegisterSvc = server
}
